// makezim —— 生成一个合成测试 ZIM（带 Xapian 标题索引与全文索引），用于没有真实数据时联调。
//
// 用法：makezim <fixtures 目录> <输出 .zim>
//   fixtures/articles/*.html   每个文件一篇文章，文件名（去掉 .html，"__" 代表 "/"）即路径，<title> 为标题
//   fixtures/redirects.tsv     每行：路径<TAB>标题<TAB>目标路径
// 另外会自动生成：
//   - 240 篇 "Synthetic topic N" 填充文章（互相链接，并大量链接核心文章，用来测试热门度排名）
//   - Long_article_test：40 个章节、约 400 段的长文（测试目录与流式翻译）
#include <zim/writer/creator.h>
#include <zim/writer/item.h>

#include <dirent.h>
#include <fstream>
#include <iostream>
#include <memory>
#include <regex>
#include <sstream>
#include <string>
#include <vector>

using namespace zim::writer;

static std::string readFile(const std::string &p) {
    std::ifstream f(p, std::ios::binary);
    std::stringstream ss;
    ss << f.rdbuf();
    return ss.str();
}

static std::string titleOf(const std::string &html, const std::string &fallback) {
    std::smatch m;
    static const std::regex re("<title>([^<]*)</title>");
    if (std::regex_search(html, m, re)) return m[1];
    return fallback;
}

static std::string page(const std::string &title, const std::string &body) {
    return "<!DOCTYPE html>\n<html class=\"client-js\"><head><meta charset=\"UTF-8\"><title>" + title +
           "</title><link href=\"./_mw_/style.css\" rel=\"stylesheet\"><script src=\"./_res_/script.js\"></script></head>"
           "<body class=\"mw-body mw-body-content mediawiki\"><div id=\"content\" class=\"mw-body\"><h1 id=\"firstHeading\" class=\"firstHeading mw-first-heading\">" +
           title + "</h1><div id=\"bodyContent\"><div id=\"mw-content-text\" class=\"mw-body-content\"><div class=\"mw-content-ltr mw-parser-output\" lang=\"en\" dir=\"ltr\">" +
           body + "</div></div></div></div></body></html>";
}

static const char *kWords[] = {"river", "mountain", "theory", "empire", "language", "music", "energy", "planet", "ocean", "city",
                               "history", "culture", "science", "machine", "garden", "festival", "railway", "library", "island", "bridge"};

int main(int argc, char **argv) {
    if (argc < 3) {
        std::cerr << "usage: makezim <fixtures dir> <out.zim>\n";
        return 2;
    }
    std::string dir = argv[1];
    std::string out = argv[2];
    Hints front = {{FRONT_ARTICLE, 1}};

    Creator c;
    c.configIndexing(true, "eng").configNbWorkers(2).configVerbose(false);
    c.startZimCreation(out);
    c.addMetadata("Name", "wikipedia_en_synthetic_test");
    c.addMetadata("Title", "Synthetic Wikipedia (test)");
    c.addMetadata("Description", "Synthetic test archive generated by makezim");
    c.addMetadata("Language", "eng");
    c.addMetadata("Creator", "Wikipedia");
    c.addMetadata("Publisher", "makezim");
    c.addMetadata("Date", "2026-10-05");

    std::vector<std::string> core;
    int count = 0;
    std::string adir = dir + "/articles";
    if (DIR *d = opendir(adir.c_str())) {
        while (struct dirent *e = readdir(d)) {
            std::string name = e->d_name;
            if (name.size() < 6 || name.substr(name.size() - 5) != ".html") continue;
            std::string path = name.substr(0, name.size() - 5);
            size_t pos;
            while ((pos = path.find("__")) != std::string::npos) path.replace(pos, 2, "/");
            std::string html = readFile(adir + "/" + name);
            std::string title = titleOf(html, path);
            c.addItem(StringItem::create(path, "text/html", title, front, html));
            if (path != "Main_Page") core.push_back(path);
            count++;
        }
        closedir(d);
    }

    // 一个非 HTML 资源，测试 mimetype 过滤
    c.addItem(StringItem::create("_mw_/style.css", "text/css", "", Hints{}, "body{color:red}"));

    // 填充文章
    const int N = 240;
    for (int i = 1; i <= N; i++) {
        std::ostringstream b;
        b << "<p><b>Synthetic topic " << i << "</b> is a generated article about the " << kWords[i % 20] << " of "
          << kWords[(i * 7) % 20] << ". It links to ";
        // 越靠前的核心文章被链接越多次（构造入链差异）
        for (size_t k = 0; k < core.size(); k++) {
            if (i % (int)(k + 1) == 0) b << "<a href=\"./" << core[k] << "\" title=\"" << core[k] << "\">" << core[k] << "</a>, ";
        }
        b << "and <a href=\"./Synthetic_topic_" << (i % N) + 1 << "\">the next topic</a>.</p>";
        b << "<div class=\"mw-heading mw-heading2\"><h2 id=\"Overview\">Overview</h2></div><p>The " << kWords[(i * 3) % 20]
          << " described here is imaginary and exists only for testing search and ranking.</p>";
        std::string path = "Synthetic_topic_" + std::to_string(i);
        std::string title = "Synthetic topic " + std::to_string(i);
        c.addItem(StringItem::create(path, "text/html", title, front, page(title, b.str())));
        count++;
    }

    // 长文
    {
        std::ostringstream b;
        b << "<p>The <b>long article test</b> is a deliberately long page used to check the outline sidebar, smooth scrolling and "
             "streaming translation of many paragraphs.</p>";
        for (int s = 1; s <= 40; s++) {
            b << "<div class=\"mw-heading mw-heading2\"><h2 id=\"Section_" << s << "\">Section " << s << ": the "
              << kWords[s % 20] << "</h2><span class=\"mw-editsection\"><span class=\"mw-editsection-bracket\">[</span><a href=\"#\">edit</a><span class=\"mw-editsection-bracket\">]</span></span></div>";
            for (int p = 1; p <= 10; p++) {
                b << "<p>Paragraph " << p << " of section " << s << " talks about the " << kWords[(s + p) % 20] << " and the "
                  << kWords[(s * p) % 20] << ". Researchers have studied how the " << kWords[(s + 2 * p) % 20]
                  << " changed over the centuries, and many people still visit it every year.<sup id=\"cite_ref-" << s << "_" << p
                  << "\" class=\"reference\"><a href=\"#cite_note-" << s << "\">[" << s << "]</a></sup></p>";
            }
            if (s % 5 == 0) {
                b << "<div class=\"mw-heading mw-heading3\"><h3 id=\"Subsection_" << s << "\">Subsection " << s << "</h3></div><ul>";
                for (int k = 1; k <= 4; k++) b << "<li>List item " << k << " about the " << kWords[(s + k) % 20] << ".</li>";
                b << "</ul>";
            }
        }
        b << "<div class=\"mw-heading mw-heading2\"><h2 id=\"References\">References</h2></div><div class=\"mw-references-wrap\"><ol class=\"references\">";
        for (int s = 1; s <= 40; s++) b << "<li id=\"cite_note-" << s << "\"><span class=\"mw-cite-backlink\"><a href=\"#cite_ref-" << s << "_1\">^</a></span> <span class=\"reference-text\">Reference number " << s << ".</span></li>";
        b << "</ol></div>";
        c.addItem(StringItem::create("Long_article_test", "text/html", "Long article test", front, page("Long article test", b.str())));
        count++;
    }

    // 重定向
    std::ifstream rf(dir + "/redirects.tsv");
    std::string line;
    while (std::getline(rf, line)) {
        if (line.empty() || line[0] == '#') continue;
        std::istringstream ls(line);
        std::string path, title, target;
        std::getline(ls, path, '\t');
        std::getline(ls, title, '\t');
        std::getline(ls, target, '\t');
        if (!path.empty() && !target.empty()) c.addRedirection(path, title, target, front);
    }

    c.setMainPath("Main_Page");
    c.finishZimCreation();
    std::cout << "wrote " << out << " (" << count << " articles)\n";
    return 0;
}
